name: flutter_clean_arch_tdd_bloc
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  dartz: ^0.10.1
  data_connection_checker: ^0.3.4
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.11
  bloc: ^8.0.1
  flutter_bloc: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.17


flutter:
  uses-material-design: true
  assets:
    - test/fixtures/